**1. What is the purpose of the np.tile function?**

The np.tile function constructs a new array by repeating an input array the number of times specified by the reps parameter.


**2. Explain the use of the np.repeat function.**

The np.repeat function repeats elements of an array along a specified axis.


**3. What is the difference between np.vstack and np.hstack?**

np.vstack stacks arrays vertically (row-wise), while np.hstack stacks arrays horizontally (column-wise).


**4. How can you add a new axis to an array in Numpy?**

A new axis can be added using np.newaxis or None within the array indexing.

**5. Discuss the use of the np.meshgrid function.**





The np.meshgrid function creates coordinate matrices from coordinate vectors, useful for evaluating functions on a grid.


**6. Repeat the elements of a 1D Numpy array three times.**





In [6]:
array = np.array([1, 2, 3])
repeated_array = np.repeat(array, 3)
print("Repeated array:", repeated_array)

Repeated array: [1 1 1 2 2 2 3 3 3]


**7. Tile a 2x2 matrix into a 4x4 matrix.**

In [7]:
matrix = np.array([[1, 2], [3, 4]])
tiled_matrix = np.tile(matrix, (2, 2))
print("Tiled 4x4 matrix:\n", tiled_matrix)


Tiled 4x4 matrix:
 [[1 2 1 2]
 [3 4 3 4]
 [1 2 1 2]
 [3 4 3 4]]


**8.Use np.meshgrid to create a grid of points from two 1D arrays.**


In [8]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
X, Y = np.meshgrid(x, y)
print("X:\n", X)
print("Y:\n", Y)

X:
 [[1 2 3]
 [1 2 3]
 [1 2 3]]
Y:
 [[4 4 4]
 [5 5 5]
 [6 6 6]]


**9. Stack two 1D arrays of different lengths horizontally after padding the shorter one with zeros.**

In [9]:
array1 = np.array([1, 2, 3, 4])
array2 = np.array([5, 6])
padded_array2 = np.pad(array2, (0, len(array1) - len(array2)), 'constant')
stacked_horizontally = np.hstack((array1, padded_array2))
print("Horizontally stacked arrays after padding:\n", stacked_horizontally)


Horizontally stacked arrays after padding:
 [1 2 3 4 5 6 0 0]


**10. Add a new axis to a 1D array to convert it into a row vector.**

In [10]:
array = np.array([1, 2, 3])
row_vector = array[np.newaxis, :]
print("Row vector:\n", row_vector)

Row vector:
 [[1 2 3]]
