1. what is the shape of an array and how can it be accessed? 

The shape of an array is a tuple representing the dimensions of the array, which can be accessed using the .shape attribute.


2. Explain the difference between reshaping and flattening an array.

Reshaping changes the structure of the array to a different shape without changing its data, while flattening converts a 
multi-dimensional array into a 1D array.


3. How do you stack arrays vertically and horizontally in Numpy?


Arrays can be stacked vertically using np.vstack and horizontally using np.hstack.


4. What does the np.newaxis object do in Numpy?


The np.newaxis object increases the dimension of the array by one, making it possible to convert a 1D array into a 2D row or column vector.


5. Discuss the use of the np.concatenate function.


The np.concatenate function is used to join two or more arrays along an existing axis.
Programming Tasks


6. shape a 1D array of 12 elements into a 3x4 matrix.

In [3]:
import numpy as np
array_1d = np.arange(12)
reshaped_array = array_1d.reshape(3, 4)
print("Reshaped 3x4 array:\n", reshaped_array)


Reshaped 3x4 array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


7. Flatten a 2D array back into a 1D array.

In [4]:
flattened_array = reshaped_array.flatten()
print("Flattened array:", flattened_array)


Flattened array: [ 0  1  2  3  4  5  6  7  8  9 10 11]


8. Stack two 1D arrays of the same length vertically.



In [6]:
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])
stacked_vertically = np.vstack((array1, array2))
print("Vertically stacked arrays:\n", stacked_vertically)


Vertically stacked arrays:
 [[1 2 3]
 [4 5 6]]


9. Horizontally stack two 2D arrays of compatible shapes.



In [7]:
array3 = np.array([[1, 2], [3, 4]])
array4 = np.array([[5, 6], [7, 8]])
stacked_horizontally = np.hstack((array3, array4))
print("Horizontally stacked arrays:\n", stacked_horizontally)


Horizontally stacked arrays:
 [[1 2 5 6]
 [3 4 7 8]]


10. Use np.newaxis to convert a 1D array into a column vector.



In [8]:
array = np.array([1, 2, 3])
column_vector = array[:, np.newaxis]
print("Column vector:\n", column_vector)

Column vector:
 [[1]
 [2]
 [3]]
