In [ ]:
Question 1: Create a 1D numpy array of the first 10 natural numbers.

In [1]:
import numpy as np

array_1d = np.arange(1, 11)
print("1D array of the first 10 natural numbers:", array_1d)


1D array of the first 10 natural numbers: [ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
Question 2: Create a 2D numpy array of shape (3, 4) with values ranging from 10 to 21 (exclusive).

In [2]:
array_2d = np.arange(10, 22).reshape(3, 4)
print("2D array of shape (3, 4) with values from 10 to 21:\n", array_2d)

2D array of shape (3, 4) with values from 10 to 21:
 [[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]


In [ ]:
Question 3: Create a 3x3 numpy array with random values and find the mean of the array.

In [3]:
random_array = np.random.random((3, 3))
mean_value = np.mean(random_array)
print("3x3 random array:\n", random_array)
print("Mean of the array:", mean_value)


3x3 random array:
 [[0.20664348 0.06565249 0.56539792]
 [0.25496635 0.90866635 0.45213876]
 [0.97168607 0.8669042  0.89286051]]
Mean of the array: 0.5761017917532847


In [ ]:
Question 4: Create a numpy array with 20 linearly spaced values between 1 and 5.

In [4]:
linear_array = np.linspace(1, 5, 20)
print("20 linearly spaced values between 1 and 5:\n", linear_array)


20 linearly spaced values between 1 and 5:
 [1.         1.21052632 1.42105263 1.63157895 1.84210526 2.05263158
 2.26315789 2.47368421 2.68421053 2.89473684 3.10526316 3.31578947
 3.52631579 3.73684211 3.94736842 4.15789474 4.36842105 4.57894737
 4.78947368 5.        ]


In [ ]:
Question 5: Create a numpy array of shape (4, 4) and fill it with a checkerboard pattern (alternating 0s and 1s).

In [5]:
checkerboard_array = np.zeros((4, 4), dtype=int)
checkerboard_array[1::2, ::2] = 1
checkerboard_array[::2, 1::2] = 1
print("4x4 checkerboard pattern:\n", checkerboard_array)


4x4 checkerboard pattern:
 [[0 1 0 1]
 [1 0 1 0]
 [0 1 0 1]
 [1 0 1 0]]


In [ ]:
Question 6: Create a 5x5 identity matrix using numpy.


In [6]:
identity_matrix = np.eye(5)
print("5x5 identity matrix:\n", identity_matrix)


5x5 identity matrix:
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [ ]:
Question 7: Create a numpy array by repeating the array [1, 2, 3] five times.


In [7]:
repeated_array = np.tile([1, 2, 3], 5)
print("Array [1, 2, 3] repeated five times:", repeated_array)


Array [1, 2, 3] repeated five times: [1 2 3 1 2 3 1 2 3 1 2 3 1 2 3]


In [ ]:
Question 8: Create a numpy array of shape (4, 4) with random integers between 0 and 10, and then replace all values greater than 5 with 5.


In [8]:
random_int_array = np.random.randint(0, 11, size=(4, 4))
print("Original 4x4 array with random integers between 0 and 10:\n", random_int_array)

random_int_array[random_int_array > 5] = 5
print("Array with values greater than 5 replaced by 5:\n", random_int_array)


Original 4x4 array with random integers between 0 and 10:
 [[ 2  9  5  7]
 [ 0 10  6  0]
 [ 8  4  1  6]
 [ 3  1  2  6]]
Array with values greater than 5 replaced by 5:
 [[2 5 5 5]
 [0 5 5 0]
 [5 4 1 5]
 [3 1 2 5]]


In [ ]:
Question 9: Find the sum of all the elements in a 2D numpy array.


In [9]:
array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
total_sum = np.sum(array_2d)
print("2D array:\n", array_2d)
print("Sum of all elements:", total_sum)


2D array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Sum of all elements: 45


In [ ]:
Question 10: Compute the dot product of two 1D arrays: [1, 2, 3] and [4, 5, 6].


In [10]:
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])
dot_product = np.dot(array1, array2)
print("Dot product of [1, 2, 3] and [4, 5, 6]:", dot_product)


Dot product of [1, 2, 3] and [4, 5, 6]: 32
