1. What is Numpy and why is it used in scientific computing?

Numpy is a fundamental package for scientific computing in Python. 
It provides support for arrays, matrices, and numerous mathematical 
functions to operate on these data structures efficiently.

2. Describe the difference between a Python list and a Numpy array.

Python lists can hold different data types and are dynamic, 
while Numpy arrays are homogeneous (can only hold one data type) 
and provide better performance and more efficient storage.

3. Explain the concept of vectorization in Numpy.

Vectorization allows performing element-wise operations on arrays without explicit loops, making the code more concise and faster.

4. What are the main advantages of using Numpy arrays over traditional Python lists?

Numpy arrays provide better performance (speed and memory efficiency), more functionality for mathematical operations, 
and support for multi-dimensional data structures.

5. Define the term "broadcasting" in the context of Numpy arrays.

Broadcasting allows Numpy to perform arithmetic operations on arrays of different shapes by automatically expanding their dimensions to be compatible.

6. Create a 1D Numpy array with elements from 10 to 50.

In [3]:
import numpy as np
array_1d = np.arange(10, 51)
print("1D array with elements from 10 to 50:", array_1d)


1D array with elements from 10 to 50: [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


7. Create a 3x3 identity matrix.

In [4]:
identity_matrix = np.eye(3)
print("3x3 identity matrix:\n", identity_matrix)


3x3 identity matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


8. Generate a Numpy array with 15 random numbers between 0 and 1.

In [5]:
random_array = np.random.rand(15)
print("Array with 15 random numbers between 0 and 1:", random_array)

Array with 15 random numbers between 0 and 1: [0.51893696 0.72727024 0.00736624 0.68516637 0.52337335 0.02767104
 0.24983367 0.2159359  0.28965443 0.88448212 0.90533624 0.52707821
 0.08445504 0.40965865 0.9007854 ]


9. Create a 4x4 matrix with values ranging from 0 to 15.

In [6]:
matrix_4x4 = np.arange(16).reshape(4, 4)
print("4x4 matrix with values ranging from 0 to 15:\n", matrix_4x4)

4x4 matrix with values ranging from 0 to 15:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


10. Create a Numpy array of 20 evenly spaced values between 0 and 5.

In [7]:
evenly_spaced_array = np.linspace(0, 5, 20)
print("Array of 20 evenly spaced values between 0 and 5:\n", evenly_spaced_array)

Array of 20 evenly spaced values between 0 and 5:
 [0.         0.26315789 0.52631579 0.78947368 1.05263158 1.31578947
 1.57894737 1.84210526 2.10526316 2.36842105 2.63157895 2.89473684
 3.15789474 3.42105263 3.68421053 3.94736842 4.21052632 4.47368421
 4.73684211 5.        ]
